# Generated by Django 4.2.3 on 2023-07-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_book_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='creado_el',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='seller',
            new_name='vendedor',
        ),
    ]
