# Generated by Django 4.2.3 on 2023-07-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_author_book_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creado_el',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='imagen',
            new_name='imagen_del_libro',
        ),
    ]
