# Generated by Django 4.2.3 on 2023-07-15 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_creado_el_book_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
